// Package match GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package match

import "github.com/swaggo/swag"

const docTemplatematch = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ming Hsu",
            "email": "minghsu0107@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/match": {
            "get": {
                "description": "Websocket initialization endpoint for matching another user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Match another user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "session id cookie",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ErrResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfomatch holds exported Swagger Info so clients can modify it
var SwaggerInfomatch = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Match Service Swagger API",
	Description:      "Match service API",
	InfoInstanceName: "match",
	SwaggerTemplate:  docTemplatematch,
}

func init() {
	swag.Register(SwaggerInfomatch.InstanceName(), SwaggerInfomatch)
}
